pipeline {
    agent any
    environment {
        APPLICATION_NAME = 'mypythonproject'
        GIT_REPO="https://github.com/davidfireblade/mypythonproject.git"
    }
    stages {
        stage('create') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                            // create a new application from the templatePath
                            openshift.newApp("https://github.com/davidfireblade/mypythonproject.git")
                        }
                    }
                } // script
            } // steps
        } // stage
    }
}